# Generated by Django 5.0.1 on 2024-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_info', models.TextField()),
                ('advice', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('sub_info_image', models.ImageField(upload_to='media/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Pages',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bg_image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Service Post',
                'verbose_name_plural': 'Services Posts',
            },
        ),
    ]
