# Generated by Django 5.0.1 on 2024-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_servicepost_post_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='info',
        ),
        migrations.AddField(
            model_name='pages',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
