# Generated by Django 5.0.1 on 2024-02-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_post_info_pages_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
    ]
