# Generated by Django 5.0.1 on 2024-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_post_description_remove_post_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='sub_info_image',
        ),
    ]
