# Generated by Django 5.0.1 on 2024-02-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_pages_advice_remove_pages_sub_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='image',
        ),
    ]
