# Generated by Django 5.0.1 on 2024-02-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_info_pages_sub_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
