# Generated by Django 5.0.1 on 2024-02-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_delete_pages_remove_post_bg_image_post_sub_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
