# Generated by Django 5.0.1 on 2024-02-20 07:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_post_service_alter_service_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='service',
            name='body',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
