# Generated by Django 5.0.1 on 2024-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regestrstion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='your name', max_length=50)),
                ('email', models.EmailField(help_text='your email', max_length=255)),
                ('phone', models.IntegerField(help_text='your phone')),
                ('enquiry', models.CharField(help_text='your enquiry', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
