# Generated by Django 5.0.1 on 2024-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, help_text='Write author', max_length=30, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default', upload_to='blog/photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Write title', max_length=255, verbose_name='title'),
        ),
    ]
