# Generated by Django 5.0.1 on 2024-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_post_author_post_photo_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(help_text='Write author', max_length=30, verbose_name='author')),
                ('photo', models.ImageField(default='default', upload_to='blog/photos/', verbose_name='photo')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub_title')),
            ],
            options={
                'verbose_name': 'Post2',
                'verbose_name_plural': 'Posts2',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
