# Generated by Django 5.0.1 on 2024-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_post2_delete_author_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='photo',
        ),
        migrations.AddField(
            model_name='post2',
            name='image',
            field=models.ImageField(default=1, upload_to='post2/image', verbose_name='photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post2',
            name='author',
            field=models.CharField(max_length=30, verbose_name='author'),
        ),
    ]
