# Generated by Django 5.0.1 on 2024-02-18 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_author_delete_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sm_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('sub_info', models.TextField()),
                ('advice', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('sub_info_image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.socialmedia')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bg_image', models.ImageField(upload_to='media/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Team Post',
                'verbose_name_plural': 'Team Posts',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
